text = {"-- Guard 1",
"Guard 1 approaches!",
"Guard 1: Attack 10{n}A very easy enemy{n}As long as you paid attention...",
"Insult",
"You told Guard 1 that he was keeping you from your goals.{n}He got more upset",
"You told Guard 1 that he wasn't snakey enough.{n}He got more upset",
"Compliment",
"You told Guard 1 that he was good at his job.{n}He became very happy.",
"You told Guard 1 that his snakeyness was enough to become a guard{n}He became very happy.",
"You befriended Guard 1{n}He dropped a keycard",
"-- Guard 2",
"Guard 2 approaches!",
"Guard 2: Attack 15{n}Its a guard boi",
"Cheer",
"You told Guard 2 that you hate humans too{n}He is fine with your existence now",
"You told Guard 2 that your fine with Sneeks{n} He is fine with you now",
"Talk",
"You told Guard 2 that you defeated Guard 1{n}That was pretty obvious",
"You told Guard 2 that humans are kind{n}He chuckles",
"You befriended Guard 2{n}He dropped a keycard",
"-- Guard 3",
"Guard 3 approaches!",
"Guard 3: Attack 20{n}Learn how walls work ... fast",
"Poke",
"You poke Guard 3{n}That was mean",
"You poke Guard 3 very hard{n}He considers raising his attack",
"Honor",
"You tell Guard 3 you respect him{n}He likes you more than he did",
"You tell Guard 3 you don't mind if he wins{n}He respects that",
"You befriended Guard 3{n}He dropped a keycard",
"--Items",
"Your inventory is full!",
"--Shield Text",
"You picked up a Shield!",
"Defense: 10%{n}You equiped a shield!",
"--Health Potion",
"You picked up a Health Potion!",
"You drank a health potion!{n}You gained 10 HP",
"--Blue Keycard",
"You picked up the Blue Keycard",
"You can't use a keycard in battle!",
"--Red Keycard",
"You picked up the Red Keycard",
"--Green Keycard",
"You picked up the Green Keycard",
"--Guard 4",
"Guard 4 is ticked!",
"Guard 4: Attack 20{n}How on earth did you escape the cells",
"Talk",
"You talk to Guard 4 about the weather{n}He seems chill",
"There is nothing new to talk to Guard 4 about",
"Gift",
"Why would you give a gift to someone you haven't talked to{n}Weirdo",
"Guard 4 has gotten to know you{n}He accepts your gift",
"Guard 4 is now your best friend!"
}