    text = {"-- Prototype",
"Prototype approaches!",
"Prototype: Attack 10 {n}  If you are seeing this, there is a problem.",
"Insult",
"You told Guard 1 that he was keeping you from his goals. {n} He got more upset",
"You told Guard 1 that he wasn't snakey enough. {n} He got more upset",
"Complement",
"You told Guard 1 that he was good at his job. {n} He became very happy.",
"You told Guard 1 that his snakeyness was enough to become a guard. {n} He became very happy.",
"You spared Prototype!",
"-- Old Grandpa",
"Old Grandpa approaches!",
"Old Grandpa: Attack 15 {n} So old his attacks barely deal damage",
"Cheer",
"You told Old Grandpa you liked him no matter his age {n} He warms up to you",
"You told Old Grandpa you would support his decisions {n} He warms up to you",
"Talk",
"You talked to Old Grandpa about the alien planet {n} He feels uncomfortable",
"You talked to Old Grandpa about the alien king {n} He feels uncomfortable",
"You spared Old Grandpa",
}