    text = {"-- Prototype",
"Guard 1 approaches!",
"Guard 1: Attack 10 {n}  A very easy enemy{n}As long as you paid attention...",
"Insult",
"You told Guard 1 that he was keeping you from your goals. {n} He got more upset",
"You told Guard 1 that he wasn't snakey enough. {n} He got more upset",
"Complement",
"You told Guard 1 that he was good at his job. {n} He became very happy.",
"You told Guard 1 that his snakeyness was enough to become a guard. {n} He became very happy.",
"You spared Prototype!",
"-- Guard 2",
"Guard 2 approaches!",
"Guard 2: Attack 15 {n} Its a guard boi",
"Cheer",
"You told Guard 2 that you hate humans too{n} He is fine with your existence now",
"You told Guard 2 that your fine with Sneeks{n} He is fine with you now",
"Talk",
"You told Guard 2 that you defeated Guard 1 {n} That was pretty obvious",
"You told Guard 2 that humans are kind {n} He chuckles",
"You spared Guard 2",
}